# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
run-name: ${{ github.actor }} has triggered the Workflow job of ${{github.repository}}

on:
  push:
    branches: [ "master" ]

jobs:

  windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install 

    - name: Send E-Mail Notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: test.smithy2988@gmail.com
        password: ndwdtfbyavtyxtuw

        from: Github Actions
        to: gopalg@testrig.co.in
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has [ ${{ job.status }} ], Refer to attached Report for Details!
        attachments: ./src/test/resources/config/config.properties
        

#   ubuntu-latest:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Set up Xvfb
#       run: |
#           sudo apt-get update
#           sudo apt-get install -y xvfb
#           export DISPLAY=:99
#           Xvfb :99 -screen 0 1024x768x16 &
#     - uses: actions/checkout@v3
#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#         cache: maven
#     - name: Build with Maven
#       run: mvn clean install 
